Repository AY2324S1-CS2103T-W11-3/tp, pull requests merged in 2023-11, with the labels that each got.

#133 Fix test bleeding bug
  src/test/java/seedu/address/model/band/UniqueBandListTest.java
Labels: type.Bug

#134 Updated UG Introduction, Quick Start, and table of contents
  docs/UserGuide.md
Labels: type.Doc

#140 Modify the GUI behaviour after certain commands to minimise confusion
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High, type.Bug

#137 Enhancement to the "add musician to band" feature
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/band/AddMusicianToBandCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/band/AddMusicianToBandCommandParser.java
  src/main/java/seedu/address/logic/parser/band/FindBandCommandParser.java
  src/test/java/seedu/address/logic/commands/AddMusicianToBandCommandTest.java
Labels: priority.High, type.Enhancement

#143 Refactor ListCommand and add ListAllTagCommand
  src/main/java/seedu/address/logic/commands/general/ListCommand.java
  src/main/java/seedu/address/logic/commands/musician/ListAllTagsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/tag/Genre.java
  src/main/java/seedu/address/model/tag/Instrument.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/musician/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium, type.Enhancement

#144 Fix errors and customise the command messages for our application
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/band/AddMusicianToBandCommand.java
  src/main/java/seedu/address/logic/commands/band/FindBandCommand.java
  src/main/java/seedu/address/logic/commands/musician/AddCommand.java
  src/main/java/seedu/address/logic/commands/musician/EditCommand.java
  src/main/java/seedu/address/model/tag/Genre.java
  src/main/java/seedu/address/model/tag/Instrument.java
  src/test/java/seedu/address/logic/commands/FindBandCommandTest.java
Labels: priority.High, type.Bug

#148 Add invalid argument checks for the find command
  src/main/java/seedu/address/logic/commands/musician/FindCommand.java
  src/main/java/seedu/address/logic/parser/musician/FindCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.High, type.Bug

#150 Edit User Guide for band commands
  docs/UserGuide.md
Labels: type.Doc

#151 Fix bug: existing phone or email are invalid
  src/main/java/seedu/address/logic/commands/musician/AddCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/musician/Musician.java
  src/main/java/seedu/address/model/musician/UniqueMusicianList.java
  src/test/java/seedu/address/logic/commands/AddBandCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMusicianToBandCommandTest.java
  src/test/java/seedu/address/logic/commands/musician/AddCommandTest.java
Labels: priority.High, severity.High, type.Bug

#152 Add musician to band enhancement
  src/main/java/seedu/address/logic/parser/band/AddMusicianToBandCommandParser.java
Labels: priority.High, type.Bug

#154 User guide updates
  docs/UserGuide.md
  docs/images/band-features/addm_after.png
  docs/images/band-features/list_all.png
  docs/images/musician-features/find_after.png
  docs/images/musician-features/list_all.png
Labels: priority.High, type.Doc

#195 Disallow multiple band indices, write corresponding tests
  src/main/java/seedu/address/logic/commands/band/AddMusicianToBandCommand.java
  src/main/java/seedu/address/logic/parser/band/AddMusicianToBandCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/band/AddBandCommandTest.java
  src/test/java/seedu/address/logic/commands/band/AddMusicianToBandCommandTest.java
  src/test/java/seedu/address/logic/parser/band/AddMusicianToBandCommandParserTest.java
Labels: priority.High, type.Bug

#200 User guide updates
  docs/UserGuide.md
Labels: type.Doc

#202 Fix documentation bugs from PE-D
  docs/UserGuide.md
Labels: type.Bug

#203 Updating UG on the instrument and genre tags, `find` feature, and `addm` feature
  docs/DeveloperGuide.md
  docs/diagrams/FindMusicianActivityDiagram.puml
  docs/diagrams/FindMusicianSequenceDiagram.puml
  docs/diagrams/TagClassDiagram.puml
  docs/diagrams/tag_style.puml
  docs/images/FindMusicianActivityDiagram.png
  docs/images/FindMusicianSequenceDiagram.png
  docs/images/TagClassDiagram.png
Labels: type.Doc

#205 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/EditMusicianActivityDiagram.puml
  docs/images/uml/ArchitectureSequenceDiagram.png
  docs/images/uml/EditMusicianActivityDiagram.png
  docs/team/wanghejin.md
Labels: type.Doc

#226 Update images in UG and landing page
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/band-features/addm_after.png
  docs/images/band-features/addm_afteradding.png
  docs/images/band-features/addm_filter.png
  docs/images/band-features/findb.png
  docs/images/band-features/list_all.png
  docs/images/band-features/listall.png
  docs/images/band-features/removem_after.png
  docs/images/band-features/removem_before.png
  docs/images/band-features/removem_error.png
  docs/images/band-features/removem_notinband.png
  docs/images/musician-features/edit_after.png
  docs/images/musician-features/edit_before.png
  docs/images/musician-features/find_after.png
Labels: type.Doc

#227 Update DG on planned enhancement
  docs/DeveloperGuide.md
Labels: type.Doc

#223 Update Yang Yi's PPP
  docs/team/yytan25.md
Labels: type.Doc

#241 Add enhancements to DG
  docs/DeveloperGuide.md
  docs/team/yytan25.md
Labels: type.Doc

#244 Fix code quality and follow design principles
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/musician/FindCommandParser.java
  src/main/java/seedu/address/model/tag/GenreMatchesPredicate.java
  src/main/java/seedu/address/model/tag/InstrumentMatchesPredicate.java
  src/main/java/seedu/address/model/tag/TagMatchesPredicate.java
Labels: type.Chore
